SET NAMES 'utf8';
CREATE TABLE `reservations` (id INT(11) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT);
SHOW TABLE STATUS LIKE 'reservations';
SHOW CREATE TABLE `reservations`;
SET NAMES 'latin1';
SHOW INDEX FROM `reservations`;
ALTER TABLE `reservations` ADD `post_id` INT  NULL  DEFAULT NULL  AFTER `id`;
SET NAMES 'utf8';
SHOW CREATE TABLE `reservations`;
SET NAMES 'latin1';
SHOW INDEX FROM `reservations`;
ALTER TABLE `reservations` ADD `meta_id` INT  NULL  DEFAULT NULL  AFTER `post_id`;
SET NAMES 'utf8';
SHOW CREATE TABLE `reservations`;
SET NAMES 'latin1';
SHOW INDEX FROM `reservations`;
ALTER TABLE `reservations` ADD `email` VARCHAR(30)  NULL  DEFAULT NULL  AFTER `meta_id`;
SET NAMES 'utf8';
SHOW CREATE TABLE `reservations`;
SET NAMES 'latin1';
SHOW INDEX FROM `reservations`;
ALTER TABLE `reservations` ADD `firstname` VARCHAR(30)  NULL  DEFAULT NULL  AFTER `email`;
SET NAMES 'utf8';
SHOW CREATE TABLE `reservations`;
SET NAMES 'latin1';
SHOW INDEX FROM `reservations`;
ALTER TABLE `reservations` ADD `lastname` VARCHAR(30)  NULL  DEFAULT NULL  AFTER `firstname`;
SET NAMES 'utf8';
SHOW CREATE TABLE `reservations`;
SET NAMES 'latin1';
SHOW INDEX FROM `reservations`;
ALTER TABLE `reservations` ADD `production_title` VARCHAR  NULL  DEFAULT ''  AFTER `lastname`;
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'NULL  DEFAULT ''  AFTER `lastname`' at line 2
ALTER TABLE `reservations` ADD `production_title` VARCHAR  NULL  DEFAULT ''  AFTER `lastname`;
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'NULL  DEFAULT ''  AFTER `lastname`' at line 2
ALTER TABLE `reservations` ADD `production_title` VARCHAR(300)  NULL  DEFAULT NULL  AFTER `lastname`;
SET NAMES 'utf8';
SHOW CREATE TABLE `reservations`;
SET NAMES 'latin1';
SHOW INDEX FROM `reservations`;
ALTER TABLE `reservations` ADD `event_date` TIMESTAMP  NULL  AFTER `production_title`;
SET NAMES 'utf8';
SHOW CREATE TABLE `reservations`;
SET NAMES 'latin1';
SHOW INDEX FROM `reservations`;
ALTER TABLE `reservations` ADD `created` TIMESTAMP  NULL  AFTER `event_date`;
SET NAMES 'utf8';
SHOW CREATE TABLE `reservations`;
SET NAMES 'latin1';
SHOW INDEX FROM `reservations`;
